service: nest-categorizer-app

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: production
  environment:
    DYNAMODB_TABLE: Posts
    OPENAI_API_KEY: ${env.OPENAI_API_KEY}
    CATEGORIZATION_PROMPT: ${env.CATEGORIZATION_PROMPT}
    AWS_REGION_CODE: ap-south-1
    
package:
  individually: true
  patterns:
    - 'node_modules/**'
    - '!node_modules/aws-sdk/**' 
    - '!test/**'
    - '!.git/**'
    - 'dist/**'

functions:
  app:
    handler: dist/main.handler
    events:
      - http:
          path: /{proxy+}
          method: any
